name: TP2 - Workflow Conditionnel et Facultatif

on: [push, workflow_dispatch]

env:
  water: cold
  fire: Global

jobs:
  job-affichage:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le contexte GitHub
        run: echo "Le workflow a ete declenche par ${{ github.actor }}"

  job-conditionnel:
    runs-on: ubuntu-latest
    if: env.water == 'cold'
    steps:
      - name: Verification de l eau
        run: echo "L eau est bien cold"

  job-facultatif-precedence:
    runs-on: ubuntu-latest
    env:
      fire: Local
    steps:
      - name: Afficher la variable fire
        run: echo "La valeur de fire est ${{ env.fire }}"
