name: TP2 - Workflow Conditionnel

on: [push, workflow_dispatch]

# Définition globale de la variable water (Exercice principal)
env:
  water: cold

jobs:
  job-affichage:
    runs-on: ubuntu-latest
    steps:
      # Exercice principal : Afficher une variable du contexte GitHub
      - name: Afficher le contexte GitHub (Auteur)
        run: echo "Le workflow a été déclenché par l'utilisateur ${{ github.actor }}"

  job-conditionnel:
    runs-on: ubuntu-latest
    # Exercice principal : Conditionner le job pour qu'il ne s'exécute que si water == cold
    if: ${{ env.water == 'cold' }}
    steps:
      - name: Vérification de l'eau
        run: echo "L'eau est bien cold ! Ce job s'exécute."
